### ISSUE TITLE
Bugs in totals

### ISSUE THREAD

**Issue by whatthefork** [ChuckMac/woocommerce-location-report#2]
I just downloaded and installed the latest from the WP repository, and tested this on a live system. The totals are not anywhere near correct. This is easy to see by comparing a regular WC standard Sales By Date report to a Sales by Country from your plugin using the same date ranges in both reports. Incredibly far off. Not sure why, but you may want to find out and fix that. I don't have time to dig into the queries myself.  

What you might do is simply copy the queries directly from the WC core, the latest 2.3.x tree .

**Comment by ChuckMac** [comment]
@whatthefork Thanks for the report.

Do you use partial refunds on your site?  WC introduced these in 2.3 and I have not yet updated the plugin to account for these.  If so that is probably the reason for the discrepancy.

I marked this for the next release.

**Comment by whatthefork** [comment]
No. It's not refunds related in any way.

**Comment by ChuckMac** [comment]
@whatthefork I've pushed out an update to the plugin.  if you want you can install this new version and see if it fixes the issue for you.

**Comment by ActionScripted** [comment]
For whatever it's worth in my own work with custom WC reporting I found that WC adds a day to their report range via end day in most instances. It might not be at all what's going on here but thought I'd share as in my case my reports were accurate to the second and the WC reports made them seem off.
