### ISSUE TITLE
Error PHP Strict Standards

### ISSUE THREAD

**Issue by anhducbkhn** [ChuckMac/woocommerce-location-report#4]
Environment:

- Server info:		nginx/1.13.1
PHP version:		5.6.30-11+deb.sury.org~trusty+3
PHP post max size:		8 MB
PHP time limit:		30
PHP max input vars:		1000
cURL version:		7.35.0, OpenSSL/1.0.2k
SUHOSIN installed:		–
MySQL version:		5.6.33
Max upload size:		2 MB
Default timezone is UTC:		
fsockopen/cURL:		ok
SoapClient:		ok
DOMDocument:	ok	
GZip:		ok
Multibyte string: ok		
Remote post:		ok
Remote get:		ok
Woocommerce: 3.1.0
Wordpress: 4.6
WooCommerce Sales By Location Report: 1.3.1

When I buy a subscription / product, I got this message in log file

>  PHP Strict Standards:  Non-static method WC_Location_Report::init() should not be called statically in /var/www/xxx/wp-content/plugins/woocommerce-sales-by-location-report/woocommerce-location-report.php on line 161

**Comment by ChuckMac** [comment]
Thanks for the report.

Should be fixed now with the latest version.
